[package]
name = "set-token"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rusqlite = "0.33.0"
serde_json = "1.0.138"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
opt-level = 3
